package ch.awerffeli.vending;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import ch.awerffeli.vending.MachineInterface;
import ch.awerffeli.vending.VendingMachine;
import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static ch.awerffeli.vending.CoinValue.*;
import static ch.awerffeli.vending.CoinValue.EURO_1;
import static ch.awerffeli.vending.CoinValue.EURO_2;
import static org.junit.Assert.*;

public class VendingMachineTest {

    MachineInterface vendingMachine;

    @Before
    public void setup() {
        vendingMachine = new VendingMachine();
    }

    @Test
    public void testInsertAndRefundCoins() {
        vendingMachine = new VendingMachine();

        List<Coin> coinsInWallet = new ArrayList();

        coinsInWallet.add(new Coin(CENT_1));
        coinsInWallet.add(new Coin(CENT_2));
        coinsInWallet.add(new Coin(CENT_2));
        coinsInWallet.add(new Coin(CENT_50));
        coinsInWallet.add(new Coin(EURO_1));
        coinsInWallet.add(new Coin(EURO_1));
        coinsInWallet.add(new Coin(EURO_2));
        coinsInWallet.add(new Coin(EURO_2));
        coinsInWallet.add(new Coin(EURO_2));
        coinsInWallet.add(new Coin(EURO_2));
        coinsInWallet.add(new Coin(EURO_2));

        vendingMachine.insertCoins(coinsInWallet);
        Map<Coin, Integer> userCoinsInMachine = vendingMachine.refundBalance();

        assertSame(1, userCoinsInMachine.get(new Coin(CENT_1)));
        assertSame(2, userCoinsInMachine.get(new Coin(CENT_2)));
        assertSame(5, userCoinsInMachine.get(new Coin(EURO_2)));

        //after refunding no money of the user should be left in the machine
        userCoinsInMachine = vendingMachine.refundBalance();
        assertSame(0, userCoinsInMachine.get(new Coin(CENT_1)));
        assertSame(0, userCoinsInMachine.get(new Coin(CENT_2)));
        assertSame(0, userCoinsInMachine.get(new Coin(CENT_50)));
        assertSame(0, userCoinsInMachine.get(new Coin(CENT_1)));
        assertSame(0, userCoinsInMachine.get(new Coin(EURO_2)));
    }

    @Test
    public void testGetAvailableCoins() {

        final HashMap<Coin, Integer> availableCoinsBefore = vendingMachine.getAvailableCoins();

        assertSame(1, availableCoinsBefore.get(new Coin(CENT_1)));
        assertSame(2, availableCoinsBefore.get(new Coin(CENT_2)));
        assertSame(5, availableCoinsBefore.get(new Coin(CENT_5)));
        assertSame(5, availableCoinsBefore.get(new Coin(EURO_1)));

        //add some coins and check test again
        List<Coin> coinsInWallet = new ArrayList();
        coinsInWallet.add(new Coin(CENT_1));
        coinsInWallet.add(new Coin(CENT_2));
        coinsInWallet.add(new Coin(CENT_2));
        vendingMachine.insertCoins(coinsInWallet);

        final HashMap<Coin, Integer> availableCoinsAfter = vendingMachine.getAvailableCoins();

        assertSame(2, availableCoinsAfter.get(new Coin(CENT_1)));
        assertSame(4, availableCoinsAfter.get(new Coin(CENT_2)));
        assertSame(5, availableCoinsAfter.get(new Coin(CENT_5)));
        assertSame(5, availableCoinsAfter.get(new Coin(EURO_1)));

    }



}
