import ch.awerffeli.vending.Coin;
import ch.awerffeli.vending.MachineInterface;
import ch.awerffeli.vending.VendingMachine;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static ch.awerffeli.vending.Coin.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        MachineInterface vendingMachine = new VendingMachine();

        List<Coin> myWallet = new ArrayList<>();
        myWallet.add(CENT_1);
        myWallet.add(CENT_2);
        myWallet.add(CENT_2);
        myWallet.add(CENT_50);
        myWallet.add(EURO_1);
        myWallet.add(EURO_1);
        myWallet.add(EURO_2);
        myWallet.add(EURO_2);
        myWallet.add(EURO_2);
        //=8.55

        vendingMachine.insertCoins(myWallet);
        String itemName = "BTC";
        if(vendingMachine.purchaseItem(itemName)) {
            System.out.println(String.format("Purchase of %s was successfull.", itemName));
        }

        final Map<Coin, Integer> refundBalance = vendingMachine.refundBalance();
        refundBalance.forEach((coin, quantity) -> System.out.println(String.format("Refunded %s x %s €", quantity, coin.getValue() / 100d)));

    }
}
