import ch.awerffeli.vending.Coin;
import ch.awerffeli.vending.Item;
import ch.awerffeli.vending.VendingMachine;

import java.util.ArrayList;
import java.util.List;

import static ch.awerffeli.vending.CoinValue.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        VendingMachine vendingVendingMachine = new VendingMachine();

        List<Coin> myWallet = new ArrayList();
        myWallet.add(new Coin(CENT_1));
        myWallet.add(new Coin(CENT_2));
        myWallet.add(new Coin(CENT_2));
        myWallet.add(new Coin(CENT_50));
        myWallet.add(new Coin(EURO_1));
        myWallet.add(new Coin(EURO_1));
        myWallet.add(new Coin(EURO_2));
        myWallet.add(new Coin(EURO_2));
        myWallet.add(new Coin(EURO_2));

        vendingVendingMachine.insertCoins(myWallet);
        vendingVendingMachine.refundBalance();

    }
}
